### ISSUE TITLE
Add `CONFIGURE_OPTS=--enable-shared`

### ISSUE THREAD

**Issue by jnewman** [CircleCI-Public/cimg-python#102]
I'm using this with pyinstaller to build executables and I have to reinstall relevant python b/c it's not installed with `CONFIGURE_OPTS=--enable-shared`. Any chance you'd do this by default?

Reference: https://github.com/pyenv/pyenv/issues/392

Thanks!

**Comment by felicianotech** [comment]
V3.9.9 and v3.10.0 should be compiled this way now. Can you confirm that your tool works now without re-compiling?

**Comment by jnewman** [comment]
Confirmed this works. Thanks!
