### ISSUE TITLE
How to explicitly specify nodejs version?

### ISSUE THREAD

**Issue by luzfcb** [CircleCI-Public/cimg-python#104]
Just over 2 hours ago, the `cimg/python:3.9-node` image was updated to point to [cimg/python:3.9.8-node](https://github.com/CircleCI-Public/cimg-python/pull/103), however, the new version updates the major version of `nodejs` from `14` to `16`. This caused the build of several of my projects to break.

I downgraded to `cimg/python:3.9.7-node` as a temporary solution, however, I would like to know how to use the latest minor version of python3.9.x and a specific version of `nodejs` at the same time.

**Comment by felicianotech** [comment]
The suggested solution when you need tight control of the Node.js version is to use the [Node.js orb](https://circleci.com/developer/orbs/orb/circleci/node). This allows you to specify the version you need regardless of the image. If you use the orb with the -node variant image, this means nvm will already be installed and so it's slightly faster.
