### ISSUE TITLE
Consider adding the `--enable-optimizations` Python configure argument

### ISSUE THREAD

**Issue by illia-v** [CircleCI-Public/cimg-python#108]
Please consider setting `CONFIGURE_OPTS="--enable-optimizations"` when Python is installed using pyenv, this enables Profile Guided Optimization resulting in a noticeable effect on Python speed.

BTW, official Python Docker images enabled this optimization some time ago, please check https://github.com/docker-library/python/issues/160.
They decided to [set `PROFILE_TASK`](https://github.com/docker-library/python/blob/2bf869e357137d4d6d5c18afbfda284848cd46d1/3.7/bullseye/Dockerfile#L50-L86) in addition to enabling optimizations when Python <= 3.7 is compiled because of some issues.

**Comment by felicianotech** [comment]
Completed: https://github.com/CircleCI-Public/cimg-python/pull/117
