### ISSUE TITLE
pip installed binaries not readily available?

### ISSUE THREAD

**Issue by felicianotech** [CircleCI-Public/cimg-python#112]
It appears for some pip binaries to be made available in PATH, `eval "$(pyenv init -)"` needs to be manually run. This needs to be investigated as that doesn't sound ideal.

**Comment by kelvintaywl** [comment]
From past GitHub issues in Pyenv, it seems there has been a recent change to how much is needed to be done to ensure Pyenv is initialized as part of $PATH.

Example Issue: https://github.com/pyenv/pyenv/issues/1906

This looks to be a recent issue (perhaps starting from a particular Pyenv version).

**Comment by adrogon** [comment]
Is the following related?

Before:
```
- image: circleci/python:3.10
- sudo pip install awscli
```
Passes.

After:
```
- image: cimg/python:3.10
- sudo pip install awscli
```
`sudo: pip: command not found`

**Comment by hyperknot** [comment]
I'm running into this as well. What I found out is that I locally have a `.python-version` file and it breaks the build environment on CircleCI. This is a recent change and it was quite difficult to debug.
Fix is to add
```
      - run: rm .python-version
```

at the top of the config.

**Comment by felicianotech** [comment]
There were some changes to the Python image a few months ago. Is anyone having this issue with images published within the past couple of months?

**Comment by mellis-at-infomedia** [comment]
I've this exact problem 3.10.  Should try a different version?

**Comment by felicianotech** [comment]
@mellis-at-infomedia When v3.10.6 came out, the alias 3.10 was updated. Which specific tag are you using? Is there a build link with the error that is for a public project?

**Comment by felicianotech** [comment]
Is everyone here trying to use pip with `sudo`? Using it without `sudo` works: https://app.circleci.com/pipelines/github/felicianotech/cci-testing-pub/795/workflows/b06c6237-8392-4375-beaf-294b576a4541/jobs/1805

**Comment by mellis-at-infomedia** [comment]
You may need to fall back to `circleci/python:3.10`, which is **not** the version CircleCI recommends and is marked as experimental, but does seem to have less of these issues

**Comment by adrogon** [comment]
@felicianotech It does work, thank you for that :blush:

**Comment by felicianotech** [comment]
I'm going to go ahead and close this. In the near future, we'll be updating this readme (as well as for the other images) and how to use package managers, such as when to use `sudo` or not. Hopefully that will make it clear since I know sometimes it's confusing.

**Comment by anilanar** [comment]
I think there are legitimate cases when pip or binaries installed by pip needs to be used with `sudo`, for example when running things that will do system-wide operations with sudo.

So I think this issue should be reopened and pip should be pre-installed for root user as well as for the non-root circleci user.
