### ISSUE TITLE
No support of geckodriver ?

### ISSUE THREAD

**Issue by tut-tuuut** [CircleCI-Public/cimg-python#123]
Hello,

I'm trying to migrate our `circleci/python:3.7.12-browsers` image to `cimg/python:3.7.12-browsers`. You can find [my PR here](https://github.com/betagouv/Aidants_Connect/pull/575/files).

All our selenium tests are failing because geckodriver is not in path, but reading cimg images documentation I'm not sure geckodriver is here at all. You can see our [test execution results](https://app.circleci.com/pipelines/github/betagouv/Aidants_Connect/3243/workflows/4506bd79-9569-4e82-ace8-be341ac0d458/jobs/3243) here.

Is it on purpose? Should we install geckodriver manually on every test run, or rollback to legacy browsers image? Thank you for your help <3

**Comment by felicianotech** [comment]
Hi,

The browsers variant for next-gen images should be used in conjunction with the [Browser Tools Orb](https://circleci.com/developer/orbs/orb/circleci/browser-tools). This will allow you to get Chrome, Firefox, Chromedriver, and geckodriver at whatever versions best suit you.

I hope that helps.
