### ISSUE TITLE
Rebuild images to include Poetry 1.2.0

### ISSUE THREAD

**Issue by pietrodn** [CircleCI-Public/cimg-python#145]
Could you please rebuild the Python images to include Poetry 1.2.0 which [has been released](https://python-poetry.org/blog/announcing-poetry-1.2.0/) on August 31?

There are some incompatibility issues about `poetry.lock` files being generated by Poetry 1.2.0 and then installed by the Poetry 1.1.7 version included in the current image, and it would help a lot to have the latest Poetry version available.

**Comment by felicianotech** [comment]
Hi. We don't rebuild images by policy. The latest version of Poetry is installed when a new image is created. If that version isn't want you need, you'll need to change it within your pipeline or with your own image (either a child image or a different one).

**Comment by pietrodn** [comment]
Understood. Thanks.
