### ISSUE TITLE
Missing virtualenv from standard Python image

### ISSUE THREAD

**Issue by mulcahys** [CircleCI-Public/cimg-python#16]
While I don't think you need/want to add every possible Python tool to the standard image - I think use of virtualenv in CI pipelines is common enough that it makes sense to include in the standard image.

**Comment by mulcahys** [comment]
Proposed #17 as one possible solution - I guess others could be to use pyenv-virtualenv or possible modify your code to use https://docs.python.org/3/library/venv.html

**Comment by gmemstr** [comment]
I think we'd be okay to pass on installing this by default and encourage the use of multiple jobs using our matrix feature (https://circleci.com/blog/circleci-matrix-jobs) if multiple versions of Python need to be tested against. Unless there's a good argument to be made, I'll go ahead and mark this as closed.
