### ISSUE TITLE
3.9.15-browsers is missing xvfb

### ISSUE THREAD

**Issue by mrdon** [CircleCI-Public/cimg-python#162]
It looks like a cleanup in b63a2ef7120f240c47b155459d1b20f010ad3ebf removed xvfb, which the 3.9.15-browsers image relies on.

**Comment by BitesizedLion** [comment]
Same for 3.8.15 with ab5a51409af3fcf2848fb3c9ddbd95b611afcacd

**Comment by felicianotech** [comment]
Could anyone provide more info on what' you're trying to do?

What are you trying to run? What's the error message?

I'm having trouble tracking this so far, the way we produce the browser variants, nothing has changed there so this is likely a lower level change in the Python or base image that I need to find.

**Comment by mrdon** [comment]
The change is in the SHA I referenced. Basically, the init script for this docker image starts up Xvfb, but that commit removed xvfb, causing an error. You can see this if you simply try to docker run bash into the image.

**Comment by tsande01** [comment]
It seems like `xvfb` used to be in the list of apt deps for installing chrome, but that whole section was removed in favor of a `sources.list`

**Comment by felicianotech** [comment]
These images have been updated and this issue should be resolved.
