### ISSUE TITLE
Upgrade poetry

### ISSUE THREAD

**Issue by brandon-leapyear** [CircleCI-Public/cimg-python#163]
Poetry 1.2.0 has a bug where `poetry self update` fails when `virtualenv` is upgraded. This started happening today because `virtualenv` just released a new version. It can be worked around by running `poetry self update` a second time, but it would be great if `cimg/python` could push a new version with an upgraded `poetry`.

More info: https://github.com/python-poetry/poetry/pull/6062#issuecomment-1291264293

**Comment by felicianotech** [comment]
Poetry is installed at the latest version at the time we publish an image. Older images won't be updated. The next release we're doing will be for Python v3.11.0.

We might have an issue with some recent releases (#161 for example) and if we need to fixt that, then Poetry would be updated in that image as well.
