### ISSUE TITLE
python 3.11

### ISSUE THREAD

**Issue by davidszotten** [CircleCI-Public/cimg-python#164]
Hi,

What's the process for getting a python 3.11 image up? Can i do anything to help?

Thanks!

**Comment by felicianotech** [comment]
We will publish it later today.

**Comment by davidszotten** [comment]
> Being held up by https://github.com/CircleCI-Public/cimg-python/issues/161 and possibly https://github.com/CircleCI-Public/cimg-python/issues/162

those look like existing regressions. while i agree that they need addressing, do we need to block people using 3.11 at all because of them?

**Comment by felicianotech** [comment]
To avoid making the problem worse, yes.

A PR has been opened for v3.11.0. Once CI passes, it will merge and then be available about an hour after that.

**Comment by davidszotten** [comment]
thank you!
