### ISSUE TITLE
Support Java 17 LTS in browser images

### ISSUE THREAD

**Issue by eydunn** [CircleCI-Public/cimg-python#188]
Would it be possible to support the current LTS version of Java - Java 17 - in the browser variant. Perhaps as an extra version of browser variant images. 

See: https://github.com/eydunn/cimg-python/tree/add-java17-version-of-browser-images

I am aware that this might need some further changes of build scripts, bare with me. :-)

Thanks.

**Comment by JalexChen** [comment]
hi @eydunn - what's the use case for including Java 17 here with Python and would this be better solved with using a similar cimg that you can install python on?

For example, [cimg-openjdk](https://github.com/CircleCI-Public/cimg-openjdk) includes Java 17 and python is already installed on that (and the versions can be modified with the python orb). In terms of supporting additional variants, I don't think that is necessarily in our plans

**Comment by eydunn** [comment]
Hi @JalexChen - yes I can see that I could use cimg-openjdk:17 instead - the only thing missing there is pip or pip3. Thank you, I will close this issue. And see if I can figure out how to go further with the other image.
