### ISSUE TITLE
Release Poetry 1.4.2 for Python 3.8 and 3.9

### ISSUE THREAD

**Issue by ralbertazzi** [CircleCI-Public/cimg-python#191]
Python 3.8 and 3.9 are still active minor versions but they haven't been updated to the latest Poetry in the last release. I'd be great to have poetry upgraded to the latest version there too

**Comment by ralbertazzi** [comment]
Actually Poetry 1.5 has been released a few days ago, so it would be great to have it on Python 3.8 onwards

**Comment by ralbertazzi** [comment]
Poetry 1.5.1 is out, any news on when we could see this released on cimg ?

**Comment by ryanbourdais** [comment]
Hi @ralbertazzi new versions of Python 3.8 and 3.9 got released earlier today so we should have a new image with updated poetry included out by the end of the day

**Comment by ryanbourdais** [comment]
The new images should now be live with the latest version of poetry. Please reopen this issue if you have any further questions or if this is not a resolution.

**Comment by ralbertazzi** [comment]
That's amazing, thank you @ryanbourdais ! However, it would be great to have a consistent support for the same tools versions across all supported Python versions - in short, it would be great to have the latest Poetry on 3.10 and 3.11 too.

It looks to me like the core issue is related to releases being possible only when a new Python version gets out, which makes it hard to stay up to date with other tools installed within the same Docker image. However, this is the only thing that you can do with the current tagging scheme, unless you go for the option of overriding existing tags, which is not ideal.

Food for thought: it might be interesting to consider changing tagging scheme to something like "python.version-year:month" (eg 3.9-23.06) like the base cimg does. At that point you could cut a fresh new release every month with the latest tools stack (and latest base cimg too!).

**Comment by ralbertazzi** [comment]
@ryanbourdais actually [3.10.12 and 3.11.4 have just been released too](https://pythoninsider.blogspot.com/2023/06/python-3114-31012-3917-3817-3717-and.html)! 😄 I don't see the Docker images released on Docker Hub yet, but could you cut a `cimg` release for those images too when they are out? 🙏

**Comment by ryanbourdais** [comment]
@ralbertazzi those images are now released
