### ISSUE TITLE
sha256:449891a8d62d87c9471b62a4ef2bd9b2ea64e581f0c5246f5a8124a817be9cd9 broke my build

### ISSUE THREAD

**Issue by timvisher** [CircleCI-Public/cimg-python#47]
I've already worked around this issue by pinning to `sha256:7ab5753b253c17c2de850abdf020fa1ae23a0e5bd2df8b14f5a54ab57d06f4eb` but I figured I'd leave this here in case it helped someone else. At first glance it appears to have something to do with me caching the virtual environment for my project and maybe the location of the python install changing or something.

If I can provide further details let me know.

**Comment by dsayling** [comment]
If you don't load from cache does the build succeed? I think this is going to help, as in the "working" sha you provided, `python` was installed in `/root/.pyenv/shims/python`. Where in the broken one its more appropriately installed in the `/home/circleci/.pyenv/shims/python`. The venv likely has a link to the old path.

As these new convenience images are in beta - were still working on making them suitable replacement for the legacy images.

Please let me know if this helps.

**Comment by timvisher** [comment]
If I can get around to it I'll give it a try. Blowing the cache was my first thought I just don't have time to try it right now.

**Comment by felicianotech** [comment]
@timvisher I'm going to go ahead and close this. If you decide to clear cache and there's still a problem, please let us know.
