### ISSUE TITLE
Will there be a `-browsers` variant?

### ISSUE THREAD

**Issue by mzgajner** [CircleCI-Public/cimg-python#59]
I hope this isn't a bad place to ask this - we're currently using `circleci/python:3.8-browsers` and `circleci/python:3.8-node-browsers`. As far as I can see there are currently no equivalent variants of these latest-gen `cimg/python` images, so unfortunately we can't migrate to them.

Are there any plans to introduce them eventually?

**Comment by felicianotech** [comment]
Yes. We'll have a beta going for this starting next week.

**Comment by bullfest** [comment]
Is there any way to get access to the beta?

**Comment by felicianotech** [comment]
@bullfest You can read about it here: https://discuss.circleci.com/t/next-gen-convenience-image-browsers-variant-beta/37794?u=felicianotech
