### ISSUE TITLE
python-version file causes image to break

### ISSUE THREAD

**Issue by apeschel** [CircleCI-Public/cimg-python#63]
If you have a project with a .python-version in it that is different than the python version included with the image, you'll get strange and mostly broken behavior.

Example:

* Create a project with a .python-version set to 3.8.5
* Load it into the python:3.8.6 image
* Attempt to run `pip install -e .` for the project
* You'll get errors about badly linked libraries

**Comment by apeschel** [comment]
I think just having the image ignore the python-version file would be fine. Can pyenv be stripped from the image?

**Comment by devkapilbansal** [comment]
@apeschel I want to look into this but as a beginner, I am not able to understand how to reproduce the bug. It would be great if you can help me with this

**Comment by dsayling** [comment]
@apeschel -  I think following the existing issues you've opened, I don't think the pyenv is the issue. We're using pyenv to support the same paths and install locations of python across all the versions the convenience image supports. If your project only supports `3.8.5`, then you should use the `3.8.5` image. In tools like pipenv, your `Pipfile` can "lock" you to a specific python version that would stop the build from happening
```
circleci@55c305602d8b:~/project$ python --version
Python 3.8.5
circleci@55c305602d8b:~/project$ cat Pipfile | grep _version
python_version = "3.8.6"
circleci@55c305602d8b:~/project$ pipenv install
Warning: Python 3.8.6 was not found on your system…
```
Also, if using just a setup.py you can specify a python version in your setup.py to make it more explicit
```
circleci@55c305602d8b:~$ cat setup.py 
from setuptools import setup
setup(
    # Your setup arguments
    python_requires='==3.8.6',  # Your supported Python ranges
)
circleci@55c305602d8b:~$ pip install -e .
Obtaining file:///home/circleci
ERROR: Package 'UNKNOWN' requires a different Python: 3.8.5 not in '==3.8.6'
```

I believe the broken behavior you're seeing in changing python versions is from the cache restore. I opened this https://github.com/CircleCI-Public/python-orb/issues/51 to address this. And included a few workarounds.

Thanks again for providing feedback on the initial release of the image and orb. Your input is extremely valuable.
