### ISSUE TITLE
Browsers/chromedriver not included in -browsers version

### ISSUE THREAD

**Issue by bullfest** [CircleCI-Public/cimg-python#67]
Hey! Thank's for uploading the `-browsers` variants.

If I'm not missing something chrome/chromedriver seems to be missing from the `-browsers` images. 
I'd expect them to be there based on how the `circleci/python/` `-browsers` variants worked. 

Has the idea of what `-browsers` variants should contain changed or is it simply missing as it's still a beta?

**Comment by felicianotech** [comment]
Hi. Correct, the idea of the `-browsers` variant has changed. It is designed to be used together with the [Browser Tools orb](https://circleci.com/developer/orbs/orb/circleci/browser-tools).

I'm doing a write up for the new browsers variant beta today where I'll explain it in more detail and provide an example. I'll update you here when that's posted.

**Comment by felicianotech** [comment]
@bullfest Okay, you can find the post [here](https://discuss.circleci.com/t/next-gen-convenience-image-browsers-variant-beta/37794?u=felicianotech).
