### ISSUE TITLE
Latest 3.8 image causing failures

### ISSUE THREAD

**Issue by henrickgoldwurm** [CircleCI-Public/cimg-python#78]
The latest `cimg/python:3.8` image is causing failures during dependency installations. I tested with an empty commit on a passing branch to confirm it wasn't an issue in my code changes. Switching to `cimg/python:3.8.7` seems to fix the issue.

![image](https://user-images.githubusercontent.com/51093934/108791769-e2076880-754d-11eb-91e0-cbc9229c7bfd.png)

**Comment by henrickgoldwurm** [comment]
Looks like it may be related to the move to 3.8.8 in #77

**Comment by dsayling** [comment]
@henrickgoldwurm - correct, using the image `cimg/python:3.8` is only tied to the major and minor versions; any patch release in cadence with the [python releases](https://github.com/python/cpython/releases) will be published and that tag overridden. If you need a specific version of python, you should specify the subminor version, e.g `cimg/python:3.8.7`.

If you intended to keep with the release cadence, it's also possible that cached dependencies from the older versions of python via pyenv are being used, see some details here: https://github.com/CircleCI-Public/python-orb/issues/51

**Comment by henrickgoldwurm** [comment]
Yup, resetting the cached dependencies fixed the issue. Thank for the quick reply!
