### ISSUE TITLE
No OS distribution variant?

### ISSUE THREAD

**Issue by Palisand** [CircleCI-Public/cimg-python#81]
I understand that these new images are Ubuntu-based but I'm wondering if they'll ever support operating system distribution names as variants in tags like the legacy images do, e.g `cimg/python:3.8-buster`.

In my case, I would prefer it if the image was Debian-based (Buster). Do I have to resort to using the legacy images in order to accomplish this or is there another way?

**Comment by felicianotech** [comment]
Hi. There's no immediate plans to support an OS base other than Ubuntu. Also, these next-gen images are designed to replace the legacy images so they will be sunsetted later this year.

A combination of running a custom Docker image and/or using Orbs might be helpful for you.
