### ISSUE TITLE
rebuild for minor pip version update

### ISSUE THREAD

**Issue by wyardley** [CircleCI-Public/cimg-python#82]
Will rebuilding this update pip to >= 21.1, and if so, could you all rebuild it for Python 3.x?

We're having our `safety` checks fail on
```
-> pip, installed 21.0.1, affected <21.1, id 40291
```

**Comment by felicianotech** [comment]
Hi. We virtually never rebuild images once they've been out there. There's two new Python release images coming out today and they contain Pip v21.1.1.

If you need a never version in an existing image, you can run `pip install --upgrade pip` in your build and it will be updated. I hope that helps.
